### ISSUE TITLE
Multi Store Support

### ISSUE THREAD

**Issue by sprankhub** [Spaggel/Tooltip#10]
This is related to #5, because it is important for the future data storage.

Currently, it is only possible to define one tooltip independent of the store. This is bad for translation purposes. One could pass the tooltip through a translation method, but then one would need to translate the tooltips code-wise, which is not very user-friendly. Hence, I think there should be a possibility to define tooltips for every store.

I suggest an additional tab in the attribute edit form "Tooltips", where for each store view, a WYSIWYG editor is shown. What do you think?

Another question when we implement this is how the data is actually stored. One column is not enough in this case. I tend to suggest an extra table, which is joined to the main table when necessary. What do you think?

**Comment by Spaggel** [comment]
Your extra tab solution sounds great to me!

Would it be possible to store the data using EAV instead of creating a separate table? 

If this isn't possible because we want to move away from the `eav_attribute` table or for some other reason, I'm fine with an extra table.

**Comment by sprankhub** [comment]
Alright, so let us go for the extra tab.

Well `eav_attribute` and `catalog_eav_attribute` are independent of the store. Hence, we could only store serialized data in a column, which is not a good idea IMHO. Hence, let us go for the extra table.

**Comment by Spaggel** [comment]
Sounds good to me. Thanks for the explanation.

**Comment by sprankhub** [comment]
Are you fine with dropping Magento 2.2 support and only support Magento 2.3? I would like to use declarative schema if possible :)

**Comment by Spaggel** [comment]
Sure, 2.2 support ends this month so that shouldn't be a huge problem.

**Comment by sprankhub** [comment]
Implemented in #13.
