### ISSUE TITLE
Tooltip and Magento 2 CE 2.2.6

### ISSUE THREAD

**Issue by Stassy** [Spaggel/Tooltip#2]
Hi,

I'm using CE 2.2.6

Install was fine and I can see "Attribute tooltip" on frontend.
I'm using it on a dropdown attribute.

On frontside, there is nothing close the Attribute.

Any Idea?
I can provide URL and admin access in private.

Thanks,
Stephane

**Comment by Spaggel** [comment]
Hi Stephane,

sorry for the delay but I currently don't have the time to help you. If you did find a solution feel free to reply or make a PR to let others know the solution. 

Thanks,
Daniel
