### ISSUE TITLE
Install fails when using table prefixes

### ISSUE THREAD

**Issue by rshaltry-vk** [Spaggel/Tooltip#23]
When running `bin/magento setup:upgrade` the following error is thrown when using table prefixes:

Unable to apply patch Spaggel\Tooltip\Setup\Patch\Data\MigrateTooltips for module Spaggel_Tooltip. Original exception message: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'm2.eav_attribute' doesn't exist, query was: DESCRIBE `eav_attribute`

**Comment by sprankhub** [comment]
Thanks for the report. Could you check if #24 solves your issue, @rshaltry-vk?
