### ISSUE TITLE
Not working in magento 2.3

### ISSUE THREAD

**Issue by ravi88026** [Spaggel/Tooltip#3]

**Comment by Spaggel** [comment]
Hi Ravi,

I'm afraid I can't help you with 2.3 support at this moment. Feel free to open a PR if you fixed it. I'll merge asap.

Thanks,
Daniel

**Comment by sprankhub** [comment]
It works for me with Magento 2.3 However, some code should be updated for Magento 2.3. I did that in #7.

**Comment by Spaggel** [comment]
Closing because PR is merged. Thanks again Simon!
