### ISSUE TITLE
Use Magento's CSS Tooltips Instead of Tooltipster

### ISSUE THREAD

**Issue by sprankhub** [Spaggel/Tooltip#4]
What do you think about using [Magento's default CSS tooltips](https://magento-devdocs.github.io/magento2-ui-library/tooltips.html) instead of using tooltipster? This should obviously improve the page performance, because we do not need a JS library anymore :) Would you mind merging a pull request?

**Comment by Spaggel** [comment]
Hi, thanks for the suggestion.

A pull request for this would be great. Thanks in advance!
